services:
  db:
    image: postgres
    container_name: sparkhacks_db
    volumes:
      - ./db:/data/postgres
    ports:
      - 5433:5432
    restart: always
    shm_size: 128mb
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: sparkhacks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 20
  sparkhacks:
    image: sparkhacks
    container_name: sparkhacks
    build: ./app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    container_name: sparkhacks_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - sparkhacks
